branches:
  only:
  - develop
  except:
  - master
language: python
python:
- 2.7
install:
- pip install pelican
script:
- make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  target-branch: master
  name: "Travis CI"
  local-dir: ./output
  on:
    branch: develop
