branches:
  only:
  - develop
  except:
  - master
git:
  depth: 1
language: python
python:
- 3.6.4
install:
- pip install pelican
- pip install markdown
- pip install pylint
- pip install restructuredtext_lint
- pip install hint
script:
- pylint --errors-only *.py
- hint content/*/*.md
- rst-lint content/*/*.rst
- make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  name: "Travis CI"
  local-dir: ./output
  on:
    branch: develop
