branches:
  only:
  - develop
  except:
  - master
git:
  depth: 1
language: python
python:
- 2.7.14
install:
- pip install pelican
- pip install markdown
- pip install pylint
script:
- pylint --errors-only *.py
- make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  name: "Travis CI"
  local-dir: ./output
  on:
    branch: develop
